@startuml

!theme plain
top to bottom direction

class Article {
   slug: varchar
   title: varchar
   body: text
   createdAt: timestamp
   updatedAt: timestamp
   authorId: integer
   description: text
   id: integer
}
class ArticleTagRelation {
   articleId: integer
   tagId: integer
}
class Comment {
   createdAt: timestamp
   updatedAt: timestamp
   articleId: integer
   authorId: integer
   body: text
   id: integer
}
class FavoritedArticleRelation {
   articleId: integer
   userId: integer
}
class FollowRelation {
   userId: integer
   followerId: integer
}
class Tag {
   name: varchar
   id: integer
}
class User {
   username: varchar
   email: varchar
   password: varchar
   bio: varchar
   imageUrl: varchar
   id: integer
}

Article                   ^-[#595959]-  User                     : "authorId:id"
ArticleTagRelation        ^-[#595959]-  Article                  : "articleId:id"
ArticleTagRelation        ^-[#595959]-  Tag                      : "tagId:id"
Comment                   ^-[#595959]-  Article                  : "articleId:id"
Comment                   ^-[#595959]-  User                     : "authorId:id"
FavoritedArticleRelation  ^-[#595959]-  Article                  : "articleId:id"
FavoritedArticleRelation  ^-[#595959]-  User                     : "userId:id"
FollowRelation            ^-[#595959]-  User                     : "userId:id"
FollowRelation            ^-[#595959]-  User                     : "followerId:id"
@enduml
